import AboutImage from "./about.jpg";
import LeadingImage from "./leading.jpg";
import ContactImage from "./contact.jpg";
import HomeHeroImage from "./home-hero-image.jpg";
import { HeroImage1, HeroImage2, HeroImage3, HeroImage4 } from "./hero";
import { OurAboutImage1, OurAboutImage2, OurAboutImage3 } from "./our-about";
import {
  newsHouseImage1,
  newsHouseImage2,
  newsHouseImage3,
  newsHouseImage4,
  newsHouseImage5,
  newsHouseImage6,
  newsHouseImage7,
  newsHouseImage8,
  newsHouseImage9,
  newsHouseImage10,
  newsHouseImage11,
  newsHouseImage12,
  newsHouseImage13,
  newsHouseImage14,
  newsHouseImage15,
  newsHouseImage16,
  newsHouseImage17,
  newsHouseImage18,
  newsHouseImage19,
} from "./news-houses";
import {
  NewsImage1,
  NewsImage2,
  NewsImage3,
  NewsImage4,
  NewsImage5,
} from "./news";
import {
  ServicesImage1,
  ServicesImage2,
  ServicesImage3,
  ServicesImage4,
  ServicesImage5,
  ServicesImage6,
  ServicesImage7,
  ServicesImage8,
  ServicesImage9,
  ServicesImage10,
  ServicesImage11,
  ServicesImage12,
  ServicesImage13,
  ServicesImage14,
  ServicesImage15,
  ServicesImage16,
  ServicesImage17,
  ServicesImage18,
  ServicesImage19,
  ServicesImage20,
  ServicesImage21,
  ServicesImage22,
  ServicesImage23,
  ServicesImage24,
  ServicesImage25,
  ServicesImage26,
  ServicesImage27,
  ServicesImage28,
  ServicesImage29,
  ServicesImage30,
  ServicesImage31,
  ServicesImage32,
  ServicesImage33,
  ServicesImage34,
  ServicesImage35,
  ServicesImage36,
} from "./services";

export {
  AboutImage,
  HeroImage1,
  HeroImage2,
  HeroImage3,
  HeroImage4,
  NewsImage1,
  NewsImage2,
  NewsImage3,
  NewsImage4,
  NewsImage5,
  LeadingImage,
  ContactImage,
  HomeHeroImage,
  OurAboutImage1,
  OurAboutImage2,
  OurAboutImage3,
  ServicesImage1,
  ServicesImage2,
  ServicesImage3,
  ServicesImage4,
  ServicesImage5,
  ServicesImage6,
  ServicesImage7,
  ServicesImage8,
  ServicesImage9,
  ServicesImage10,
  ServicesImage11,
  ServicesImage12,
  ServicesImage13,
  ServicesImage14,
  ServicesImage15,
  ServicesImage16,
  ServicesImage17,
  ServicesImage18,
  ServicesImage19,
  ServicesImage20,
  ServicesImage21,
  ServicesImage22,
  ServicesImage23,
  ServicesImage24,
  ServicesImage25,
  ServicesImage26,
  ServicesImage27,
  ServicesImage28,
  ServicesImage29,
  ServicesImage30,
  ServicesImage31,
  ServicesImage32,
  ServicesImage33,
  ServicesImage34,
  ServicesImage35,
  ServicesImage36,
  newsHouseImage1,
  newsHouseImage2,
  newsHouseImage3,
  newsHouseImage4,
  newsHouseImage5,
  newsHouseImage6,
  newsHouseImage7,
  newsHouseImage8,
  newsHouseImage9,
  newsHouseImage10,
  newsHouseImage11,
  newsHouseImage12,
  newsHouseImage13,
  newsHouseImage14,
  newsHouseImage15,
  newsHouseImage16,
  newsHouseImage17,
  newsHouseImage18,
  newsHouseImage19,
};
